local _, CLM = ...
CLM.CONSTANTS.ENCOUNTERS = {

}

CLM.CONSTANTS.ZONES = {

}

CLM.CONSTANTS.POINT_OPERATION_NOP    = 0
CLM.CONSTANTS.POINT_OPERATION_SET    = 1
CLM.CONSTANTS.POINT_OPERATION_UPDATE = 2

CLM.CONSTANTS.POINT_OPERATIONS = {
    [0] = "Nop",
    [1] = "Set",
    [2] = "Update"
}